App/django_demo/django_demo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from demo_app import views as demo_app_views

urlpatterns = [
    re_path(r'^$', demo_app_views.demo_app_view, name = 'demo_app'),
    path('admin/', admin.site.urls),
]

App/django_demo/demo_app/models.py
from django.db import models

# Create your models here.

App/django_demo/demo_app/forms.py
from django import forms
from django.forms import formset_factory

# class based form
class demo_app_form(forms.Form):
    # Decimal form with a generic widget to look nice
    input_demo = forms.DecimalField(widget=forms.NumberInput(attrs={'class':'form-control'}))

demo_app_formset = formset_factory(demo_app_form, extra = 1)

App/django_demo/demo_app/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponse
from django.urls import reverse
from django.views.generic import View, TemplateView, FormView
# Create your views here.
from demo_app import forms
from demo_app.demo_app_misc.add_5 import adder

# Function-based View
def demo_app_view(request):
    # Initialize a context_dict
    context_dict = {'Message':'Insight 4eva'}

    # get the form
    form = forms.demo_app_form(initial = {'input_demo': 5})
    formset = forms.demo_app_formset()
    # transfer to the context_dict
    context_dict['form'] = form
    context_dict['formset'] = formset
    # if the submit button is pressed
    if request.method == 'POST': # If submit is hit
        form = forms.demo_app_form(request.POST) # get the data
        formset = forms.demo_app_formset(request.POST) # get the additional data
        # Check to see if the form is valid
        if form.is_valid() and formset.is_valid():
            # transfer to the context_dict
            context_dict['input_demo'] = form.cleaned_data['input_demo']
            # generate output
            context_dict['output_demo'] = adder(context_dict['input_demo'])

            data = []
            for asd in formset:
                if 'input_demo' in asd.cleaned_data.keys():
                    data.append(asd.cleaned_data['input_demo'])

            context_dict['data'] = data
            # Respond to the http request
            return render(request, 'demo_app.html', context_dict)
    # Respond to the http request
    return render(request, 'demo_app.html', context_dict)

App/django_demo/demo_app/templates/demo_app.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block body_block %}

 <p>
   {{ Message }}
 </p>


<form method="post">
  <div class="form-group">
    {% csrf_token %}
    <p>
      {{ form }}
    </p>

    {{ formset.management_form }}
    <div id="form_set">
        {% for form in formset.forms %}
            <table class='no_error'>
                {{ form.as_table }}
            </table>
        {% endfor %}
    </div>
    <input type="button" value="Add More" id="add_more">
    <div id="empty_form" style="display:none">
        <table class='no_error'>
            {{ formset.empty_form.as_table }}
        </table>
    </div>
    <script>
        $('#add_more').click(function() {
            var form_idx = $('#id_form-TOTAL_FORMS').val();
            $('#form_set').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
            $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
        });
    </script>

    <div class="container">
      <button type="submit" class="btn btn-primary">Show the results!</button>
    </div>

    <p>
      {% if input_demo %}
      {{ input_demo }}
      {% endif %}
    </p>

    <p>
     {% if output_demo %}
     {{ output_demo }}
     {% endif %}
    </p>


    {% if data %}
    <ul>
    {% for d in data %}
      <li>{{ d }}</li>
    {% endfor %}
    </ul>
    {% endif %}
  </div>
</form>

<script src="http://code.jquery.com/jquery-2.0.0.min.js"></script>
<script src="{% static "/js/demo.js"%}"></script>

{% endblock %}

App/django_demo/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Insight Fellow!</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- <link rel="stylesheet" href="{% static 'css/base.css' %}"> -->
    <!-- <link rel="icon" type = "image/png" href="{% static 'images/squaredCircle_png.png' %}"> -->
    <script
        src="http://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous">
    </script>
  </head>
  <body>

    <div id = "head" class="container">
      <h1 id = "MyName">Insight Rules!</h1>
      <p id = "tagline" ><em>Please hire us</em></p>
      <hr id = "header_hr">
    </div>

    <div id = "body_block_div" class="container">

        {% block body_block %}
        {% endblock %}

    </div>

  </body>
</html>